Exercise 0 - Example

In [1]:
q = 31
q**4

923521

Exercise 1

In [3]:
#creating arbitrary list
def f(a, *arguments):
    print(a)
    for arg in arguments:
        print(arg)
f("A", "B", "C")

A
B
C


In [4]:
#Creating a tuple
tup1=(1, 2, 3, 4, 5, 6, 7)
print(tup1)

(1, 2, 3, 4, 5, 6, 7)


In [5]:
# Creating a Dictionary
Dict = {1: 'Creating', 2: 'A', 3: 'Dictionary'}
print(Dict)

{1: 'Creating', 2: 'A', 3: 'Dictionary'}


Exercise 2

In [24]:
import numpy as np
s = np.random.normal(0,1,100)


In [25]:
#the 10th element
print(s[9])

-0.12289735189928824


In [26]:
#printing elements from 10 to 20
print(s[9:19])

[-0.12289735  0.49186529  0.2644195  -1.91615208 -0.88905196  0.82999324
  0.54624229 -0.93694851  0.36279287 -0.32470576]


In [27]:
#printing elements more than 0
def printAbove(s, a):
    for i in range(a):
        if s[i] > 0:
            print(s[i], end = " ")
a = len(s)
printAbove(s, a)

0.42898234374480476 1.5403952624197361 0.2272668487767887 0.41682523308416447 0.36211488695575483 0.49186528531160334 0.26441950463378505 0.829993236656178 0.546242285446207 0.3627928680237357 1.3468897984379946 1.05607877342959 1.7814011397988303 0.15979702095352516 0.5112757856167776 0.4468112322649507 0.6454802820153215 1.919733699820988 0.20312934568030033 0.05615386073576046 0.42287107147241776 0.5573368852854144 0.2947769605419628 1.8130354780600157 0.4755396305115216 0.14540885236278056 2.0045277369806365 0.5736341882829972 0.1258615048037108 0.11094460805340595 0.18623081317156584 0.39314467075390974 0.642530408280059 1.504936628658502 0.5027461757385637 0.21665046637891705 0.5223459593336198 1.0441399130138607 1.9448251792655686 1.3254619861676369 0.5414969977789639 0.4858250144960863 0.7871083071863537 1.0131937353358047 1.3671583176963467 0.276588851525604 0.6101070090281434 1.2036168110675407 0.9114194855576669 

In [29]:
#2nd variant of printing elements more than 0
print(s[s>0])

[0.42898234 1.54039526 0.22726685 0.41682523 0.36211489 0.49186529
 0.2644195  0.82999324 0.54624229 0.36279287 1.3468898  1.05607877
 1.78140114 0.15979702 0.51127579 0.44681123 0.64548028 1.9197337
 0.20312935 0.05615386 0.42287107 0.55733689 0.29477696 1.81303548
 0.47553963 0.14540885 2.00452774 0.57363419 0.1258615  0.11094461
 0.18623081 0.39314467 0.64253041 1.50493663 0.50274618 0.21665047
 0.52234596 1.04413991 1.94482518 1.32546199 0.541497   0.48582501
 0.78710831 1.01319374 1.36715832 0.27658885 0.61010701 1.20361681
 0.91141949]


Exercise 3

In [140]:
def mypow(base,power):
    if power<50:
        return base**power
    if power>=50:
        print ("Power is too big")
        return -1
  

print(mypow(2,3))
print(mypow(2,50))

8
Power is too big
-1


Exercise 4

In [53]:
import numpy as np
a=np.arange(30)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [54]:
def above(x,n):
    for i in x:
        if x[i] > n:
            print(x[i], end=" ")
            
print(above(a, 5))

       

6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 None


Exercise 5

In [87]:
import numpy as np
b=np.arange(20)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [88]:
def my_ifelse(x,exp,n):
    if exp == ">":
       return x[x>n]
    if exp == "<":
       return x[x<n]
    if exp == ">=":
       return x[x>=n]
    if exp == "<=":
       return x[x<=n]
    if exp == "==":
       return x[x==n]
    else: return x

    
print(my_ifelse(b,">=",17))
print(my_ifelse(b,"x",3))

[17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Exercise 6

In [101]:
def counter (input_string):
    count_letters = {}
    for letter in input_string:
        if letter in count_letters:
                count_letters[letter] += 1
        else:
            count_letters[letter] = 1
    return count_letters

print(counter ("aleksandra"))

{'a': 3, 'l': 1, 'e': 1, 'k': 1, 's': 1, 'n': 1, 'd': 1, 'r': 1}


Exercise 7

In [139]:
def counter_sorted (input_string,reverse):
    a = {}
    for letter in sorted(input_string,reverse=reverse):
        if letter in a:
                a[letter] += 1 
        else:
            a[letter] = 1
    return a


print(counter_sorted("aleksandra",False))
print(counter_sorted("aleksandra",True))

{'a': 3, 'd': 1, 'e': 1, 'k': 1, 'l': 1, 'n': 1, 'r': 1, 's': 1}
{'s': 1, 'r': 1, 'n': 1, 'l': 1, 'k': 1, 'e': 1, 'd': 1, 'a': 3}
